apiVersion: v2
name: shlink
description: A Helm chart for Kubernetes
icon: https://shlink.io/favicon.svg

maintainers:
  - name: Neil Fernandes
    url: enroute.ai

dependencies:
  - name: mariadb
    version: "7.3.21"
    repository: "https://charts.bitnami.com/bitnami"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 2.2.1
kubeVersion: ">=1.14-0"
