kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "shlink-app.fullname" . }}
  labels:
    {{- include "shlink-app.labels" . | nindent 4 }}
data:
  servers.json: |
    {{- toJson .Values.servers | quote | nindent 4 }}
